# Hexo Configuration

# Global site configuration for json-LD generator
default_author: YOUR NAME
author_image: AUTHOR IMAGE
publisher_name: PUBLISHER NAME
publisher_logo: PUBLISHER LOGO
default_image: DEFAULT IMAGE

# Feed generation
feed:
  rss: true
  atom: true
  post_limit: 20

# Calendar
post_calendar:
  excerpt_character_limit: 0 # Number of character to truncate the excerpt, 0 no truncation
  contents_character_limit: 140 # Number of character to truncate the contents, 0 no truncation
